### ISSUE TITLE
Possible copy-and-past bug in src/Infrastructure/Field/interface/ESMF_Field_C.F90

### ISSUE THREAD

**Issue by zklaus** [esmf-org/esmf#108]
I am trying to get the update to esmpy-8.4.0 to work over at conda-forge/esmpy-feedstock#59 and am running into some issues.

Looking through the source code, I stumbled across what looks like a copy-and-paste bug in ESMF_Field_C.F90. Namely, in the following lines the source geom type is tested again for the destination part of the routine:

- https://github.com/esmf-org/esmf/blob/06c11b2896ba58762bd9f0df693d811a0c9ed191/src/Infrastructure/Field/interface/ESMF_Field_C.F90#L1381
- https://github.com/esmf-org/esmf/blob/06c11b2896ba58762bd9f0df693d811a0c9ed191/src/Infrastructure/Field/interface/ESMF_Field_C.F90#L1399
- https://github.com/esmf-org/esmf/blob/06c11b2896ba58762bd9f0df693d811a0c9ed191/src/Infrastructure/Field/interface/ESMF_Field_C.F90#L1411

I don't necessarily think this is related to my problem, but I thought I should let you know.

**Comment by theurich** [comment]
@oehmke, it looks like `srcgt` just needs to be changed to `dstgt` in these conditionals. Please review. Thanks!

**Comment by oehmke** [comment]
I took a look and I think that you’re correct. I’ll make that change.

**Comment by theurich** [comment]
@zklaus, thank you for reporting this. @oehmke corrected this in 2e8458dc89337d7ea89dcf8c64e13d103d041663. The latest beta tag [v8.5.0b09](https://github.com/esmf-org/esmf/tree/v8.5.0b09) includes this fix.
