### ISSUE TITLE
ESMF_PtrInt1D and similar types should be included in user documentation

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#113]
From a conversation with @jedwards4b : One of the output arguments from NUOPC_DriverGetComp is of type ESMF_PtrInt1D. But it seems that this type isn't documented in the user documentation, so he had to dig into the source code to determine how to access its contents.

It seems like this and similar public types should be included in user documentation.

**Comment by danrosen25** [comment]
Gerhard has added information to the NUOPC documentation. [https://earthsystemmodeling.org/docs/nightly/develop/NUOPC_refdoc/node4.html#SECTION000411100000000000000](https://earthsystemmodeling.org/docs/nightly/develop/NUOPC_refdoc/node4.html#SECTION000411100000000000000)

**Comment by danrosen25** [comment]
Longterm this should also be documented in ESMF.
