### ISSUE TITLE
ESMPy dependencies on PyPI and Anaconda are inconsistent

### ISSUE THREAD

**Issue by Zeitsperre** [esmf-org/esmf#115]
Hi ESMF developers,

I maintain a library on PyPI and conda-forge that uses ESMPy and I recently noticed that the conda-forge package for ESMPy appears to be missing a dependency (`pytest-json-report`) that is outlined as needed within the [pyproject.toml](https://github.com/esmf-org/esmf/blob/3d9b652f35039fd1af22ea69606bbbcb4b624fe1/src/addon/esmpy/pyproject.toml#L14). This is an issue as running `pip check` at the testing stage of a build on conda-forge will fail:
```
+ pip check
esmpy 8.4.0 requires pytest-json-report, which is not installed.
```
For the time being, I can add that dependency manually to my library's recipe, but it would make much more sense to list `pytest-json-report` under `optional-dependencies` for testing purposes (see: https://peps.python.org/pep-0633/).

Thanks!

**Comment by billsacks** [comment]
Thank you for pointing out this issue. Our main ESMPy maintainer is on leave. Would this be an easy thing for you to submit a Pull Request for? If so, we would welcome that.

**Comment by Zeitsperre** [comment]
Hi @billsacks, sure! I can submit something later today!

**Comment by rokuingh** [comment]
@Zeitsperre apologies for the long delay on this response.

If I'm understanding this correctly, then I think there are two possible solutions here: 1. is to make the dependencies in [esmpy/pyproject.toml](https://github.com/esmf-org/esmf/blob/develop/src/addon/esmpy/pyproject.toml) and the [conda-forge/esmpy-feedstock/recipe/meta.yaml](https://github.com/conda-forge/esmpy-feedstock/blob/main/recipe/meta.yaml) files consistent. I'm not well versed in conda-forge, but I think that would mean adding `pytest-json-report` to the `requirements: build:`  section of esmpy-feedstock/meta.yaml. However, I think you are suggesting a second solution, which is to move `pytest-json-report` from `dependencies` to `optional_dependencies` in pyproject.toml. I think this would also mean adding the optional-dependecy object from esmpy/pyproject.toml to the esmpy-feedstock/meta.yaml `test: requires:` section, something like `"ESMPy[testing]"`.

In the first case we only have to modify the meta.yaml, in the second case we need to modify both esmpy/pyproject.toml and meta.yaml. So I think my preference is for the second solution. But I'm also fine with the first solution if you have a compelling reason to go that way. Please let me know your preference.

**Comment by Zeitsperre** [comment]
@rokuingh No worries, I was on holiday as well!

I suggested the second option, as the testing dependencies of a package shouldn't be listed as the run dependencies. Conda is very deliberate in its solving for packages, and with complex packages (like ESMF) the fewer libraries that need to be solved for, the faster it will be to install. `pytest-json-report` is not needed for the average `esmpy` user, so it doesn't make sense IMO to add it to the conda-forge recipe to satisfy dependency checks.

I'll submit a PR to address this here momentarily.
