### ISSUE TITLE
Missing interface for ESMF_FieldEmptySet

### ISSUE THREAD

**Issue by tclune** [esmf-org/esmf#120]
The interface is overloaded for Grid, Mesh, XGrid, and LocStream.   But not for GeomBase.   This forces client code to insert the necessary lines of extraction (and error checking!) in multiple locations.  Better to centralize it.

MAPL will provide its own wrapper as an interim.   We could probably do a PR on this issue if you would prefer.

**Comment by tclune** [comment]
I suspect there are a handful of similar issues, but have not yet gone looking for them.  Might help for someone knowledgable with that layer to summarize the needed changes in this ticket.

**Comment by oehmke** [comment]
Added the ESMF_FieldEmptySet() interface for Geom. User (Tom C.) agreed that we could close.
