### ISSUE TITLE
ESMX component count based on esmxRun.config

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/esmf#132]
https://github.com/esmf-org/esmf/blob/5ace94338771348285e91353251ec7c3a62b4ba7/src/addon/ESMX/Driver/ESMX_Driver.F90#L153

The component count needs to match the number of components in the compDef.inc file ... which is based the components set at build time.

**Comment by theurich** [comment]
@danrosen25 - I think it is correct the way it is. The `componentCount` is the number of components at run-time. It could be less, equal, or greater than the number of components in `compDef.inc`. Those counts are independent of each other.
Are you running into any issues?

**Comment by danrosen25** [comment]
Yeah, I have a fix for it that I'm testing. the componentCount is correct but the allocation of memory for the compDef needs to match the number of components in the compDef.inc file.  So I'm writing out a new file compCnt.inc that says "integer, parameter :: componentDefCount = {}" which gets filled in with the number of components equal to the number of components in compDef.inc.

**Comment by theurich** [comment]
Yes, that is a bug. Good catch! Sounds like the right fix to me. Thanks!

**Comment by danrosen25** [comment]
Resolved and tested as part of the feature/esmx_cmake developments.
https://github.com/esmf-org/esmf/commit/e01f95c21d6116de442627b4c141e6cc62073578
