### ISSUE TITLE
ESMF, CMake and Spack: Need for possible change with Open MPI (and other MPI??)

### ISSUE THREAD

**Issue by mathomp4** [esmf-org/esmf#134]
Apologies to @theurich, this is going to be a long one.

So, one of my goals is to get GEOS/MAPL to build with Spack (mainline), and I am close. The current issue is with ESMF. So, I can do all my `spack install` commands and all is good and I can `spack load` or `module load` the resulting installations.

However, when I try and build MAPL with:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF -DCMAKE_INSTALL_PREFIX=../install-Debug -DBUILD_WITH_FLAP=NO
```
it fails at link time with (for example):
```
❯ make MAPL_cfio_r4
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOBaseMod.f.o
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOUtilMod.F90.o
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOGridMod.F90.o
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOVarInfoMod.F90.o
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOFileMod.F90.o
[  0%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOSdfMod.F90.o
[ 50%] Building Fortran object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOMod.F90.o
[ 50%] Building C object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o
[100%] Linking Fortran shared library ../lib/libMAPL_cfio_r4.dylib
ld: library not found for -lmpi_usempif08
collect2: error: ld returned 1 exit status
make[3]: *** [lib/libMAPL_cfio_r4.dylib] Error 1
make[2]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/all] Error 2
make[1]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/rule] Error 2
make: *** [MAPL_cfio_r4] Error 2
```
If I look at the verbose:
```
[ 50%] Linking Fortran shared library ../lib/libMAPL_cfio_r4.dylib
cd /Users/mathomp4/Models/MAPL-SpackLibs/MAPL/build-Debug/MAPL_cfio_r4 && /Users/mathomp4/.homebrew/brew/Cellar/cmake/3.26.1/bin/cmake -E remove /Users/mathomp4/Models/MAPL-SpackLibs/MAPL/build-Debug/lib/libMAPL_cfio_r4.dylib
cd /Users/mathomp4/Models/MAPL-SpackLibs/MAPL/build-Debug/MAPL_cfio_r4 && /Users/mathomp4/.homebrew/brew/Cellar/cmake/3.26.1/bin/cmake -E cmake_link_script CMakeFiles/MAPL_cfio_r4.dir/link.txt --verbose=1
/Users/mathomp4/.homebrew/brew/bin/gfortran -O0 -g -fcheck=all,no-array-temps -finit-real=snan -save-temps -ffree-line-length-none -fno-range-check -Wno-missing-include-dirs -fbacktrace -Wno-unused-dummy-argument -ffpe-trap=zero,overflow -fbacktrace -fallow-argument-mismatch -fallow-invalid-boz -falign-commons -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -dynamiclib -Wl,-headerpad_max_install_names -Wl,-flat_namespace -Wl,-commons,use_dylibs -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/hwloc-2.9.0-2cj3yxqouipde5nknlfzo6gcesjl7efz/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/libevent-2.1.12-gifpfhvutfsslcnmdlrbrrq57n3agv4t/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/pmix-4.2.3-l2w345dyztgz2ltsm42iefdrslwkgmrb/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/hwloc-2.9.0-2cj3yxqouipde5nknlfzo6gcesjl7efz/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/libevent-2.1.12-gifpfhvutfsslcnmdlrbrrq57n3agv4t/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/pmix-4.2.3-l2w345dyztgz2ltsm42iefdrslwkgmrb/lib -o ../lib/libMAPL_cfio_r4.dylib -install_name @rpath/libMAPL_cfio_r4.dylib CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOBaseMod.f.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOFileMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOGridMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOSdfMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOUtilMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ESMF_CFIOVarInfoMod.F90.o CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o  /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/esmf-8.4.1-p5sk3erstz4p44qqvn5wdfdfd7d735ey/lib/libesmf.dylib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-fortran-4.6.0-q2o4ogcyyrq5ud3q3cmmyyibfoe7vxpn/lib/libnetcdff.dylib -Wl,-rpath,/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/esmf-8.4.1-p5sk3erstz4p44qqvn5wdfdfd7d735ey/lib -Wl,-rpath,/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-c-4.9.0-43eaqan6feeiysjglni5ph26h25t2qqj/lib -Wl,-rpath,/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-fortran-4.6.0-q2o4ogcyyrq5ud3q3cmmyyibfoe7vxpn/lib  -Wl,-rpath,/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/parallelio-2.5.10-gnur7x6zfabstwgojgxpiea6fwrcgmkj/lib -Wl,-rpath,/Users/mathomp4/.homebrew/brew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin22/12/../../../ -Wl,-rpath,/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/esmf-8.4.1-p5sk3erstz4p44qqvn5wdfdfd7d735ey/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/esmf-8.4.1-p5sk3erstz4p44qqvn5wdfdfd7d735ey/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/esmf-8.4.1-p5sk3erstz4p44qqvn5wdfdfd7d735ey/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-c-4.9.0-43eaqan6feeiysjglni5ph26h25t2qqj/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-fortran-4.6.0-q2o4ogcyyrq5ud3q3cmmyyibfoe7vxpn/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/parallelio-2.5.10-gnur7x6zfabstwgojgxpiea6fwrcgmkj/lib -L/Users/mathomp4/.homebrew/brew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin22/12/../../../ -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lnetcdf -lnetcdff -lnetcdf -lnetcdf -lpioc -pthread /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib/libmpi_usempif08.dylib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib/libmpi_usempi_ignore_tkr.dylib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib/libmpi_mpifh.dylib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-fortran-4.6.0-q2o4ogcyyrq5ud3q3cmmyyibfoe7vxpn/lib -lnetcdff -lnetcdf -lnetcdf -lm /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-c-4.9.0-43eaqan6feeiysjglni5ph26h25t2qqj/lib/libnetcdf.dylib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/netcdf-c-4.9.0-43eaqan6feeiysjglni5ph26h25t2qqj/lib -lnetcdf /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib/libmpi.dylib
ld: library not found for -lmpi_usempif08
collect2: error: ld returned 1 exit status
make[3]: *** [lib/libMAPL_cfio_r4.dylib] Error 1
make[2]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/all] Error 2
make[1]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/rule] Error 2
make: *** [MAPL_cfio_r4] Error 2
```

After a lot of looking around, I think I tracked down the issue to ESMF. The issue when ESMF is built, I see in `esmf.mk`:
```
ESMF_F90LINKLIBS=  -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lnetcdf -lnetcdff -lnetcdf -lnetcdf -lpioc
```
and then `FindESMF.cmake` uses that:

https://github.com/esmf-org/esmf/blob/77bb22d9e2e65f99bd33bb73fe6f3aa865351288/cmake/FindESMF.cmake#L117

The problem is that *nowhere* in `esmf.mk` is this:
```
-L/path/to/openmpi/install/lib
```
in any `ESMF_F90` variable (or `ESMF_CXX` etc.)

So, CMake when it does its thing it is making link lines that have `-lmpi_usempif08`, say, but no corresponding `-L/.../lib` to go along with it and the linker (`gfortran`) fails.

Now, I think with enough sed/awk that [`libs.openmpif90_forcxx`](https://github.com/esmf-org/esmf/blob/develop/scripts/libs.openmpif90_forcxx) might be able to shove that in with the output of `mpifort -showme:libdirs`:
```
❯ mpifort --showme:libdirs
/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/hwloc-2.9.0-2cj3yxqouipde5nknlfzo6gcesjl7efz/lib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/libevent-2.1.12-gifpfhvutfsslcnmdlrbrrq57n3agv4t/lib /Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/pmix-4.2.3-l2w345dyztgz2ltsm42iefdrslwkgmrb/lib
```
and so maybe that gets added into `ESMF_F90LINKLIBS` and boom, I think it would work.[^1]

[^1]: I suppose `mpifort --showme:link` also shows it, but with include dirs sneaking in:
    ```
    ❯ mpifort --showme:link
    -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/openmpi-4.1.5-4xotvk3en5uj3wns6ig52kfubk5sq6mf/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/hwloc-2.9.0-2cj3yxqouipde5nknlfzo6gcesjl7efz/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/libevent-2.1.12-gifpfhvutfsslcnmdlrbrrq57n3agv4t/lib -L/Users/mathomp4/spack-mathomp4/opt/spack/darwin-ventura-m1/apple-clang-14.0.0/pmix-4.2.3-l2w345dyztgz2ltsm42iefdrslwkgmrb/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
    ```

But now you might be wondering: all sorts of people are using ESMF with spack including MAPL (in spack), so how does it build. I eventually tracked down the answer to this:
```
            "-DCMAKE_C_COMPILER=%s" % self.spec["mpi"].mpicc,
            "-DCMAKE_CXX_COMPILER=%s" % self.spec["mpi"].mpicxx,
            "-DCMAKE_Fortran_COMPILER=%s" % self.spec["mpi"].mpifc,
```
This is essentially saying we are going to also add:
```
-DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++
```
to our `cmake` call and so every `FC` and `LD` call `make` makes will now use `mpifort` instead of `gfortran` say.

And if I do this, it does work. But we've now said *everything* MAPL builds will now require MPI, even if it doesn't explicitly need it. This is how we used to do it in the old GEOS CVS GNU Make days, but now we have CMake and it can be more specific and could allow us to have MAPL libraries and executables without MPI. Now, I don't think we have any cases of MAPL executables not needing ESMF (and therefore MPI), but we could. And we definitely have some libraries that are ESMF/MPI free.

I guess my question for you is: would this be possible to try out? Or perhaps there is a reason ESMF does not do this? I can only say I've tried this with gfortranclang+openmpi on my M1 Mac. My guess/fear is that, say, intel+intelmpi might need something as well. I'm hoping to try a similar build soon with that, but oy is it annoying to get Intel+IntelMPI working with Spack...

**Comment by theurich** [comment]
@mathomp4 - To answer your question, the reason why we don't add the `-L` is because we don't need it. And that is because ESMF assumes that if you built with anything else but `ESMF_COMM=mpiuni` you are going to use the MPI compiler wrappers. Now you may wonder why then do we add the `-lmpi...` flags which are causing the very issue here. And for that I had to remind myself of what is going on here. It is a special case of the Darwin.gfortranclang.default configuration. Here we found that we have to actually link ESMF applications with the `mpicxx` wrapper, even if the main program is in Fortran - otherwise C++ exceptions are not working correctly in this configuration. However, `mpicxx` does not automatically link in the Fortran MPI libs, so we had to provide them in this case. Actually we only need those linker flags if the application contains explicit MPI code on the Fortran level, but some of the ESMF regression tests do, so we just generally add those flags in.

I do see how this causes issues here, and we can certainly add the `-L` linker flags. We might as well here since we are already adding the `-l` flags, so why not. 

On the other hand, I also think that if you link against and ESMF that has an MPI dependency, you should be using the MPI compiler wrappers no matter what. Or can you really assume that you get all of the flags those wrappers would be using though CMake? Honestly I have been confused about this trend to not user the wrappers (even Cray's ftn, CC, cc) under CMake. It seems strange to me, by I am maybe just old school here. Tell me, am I?

**Comment by mathomp4** [comment]
Well, the issue (and @tclune can elaborate more), is that not everything in MAPL depends on ESMF. *Most* of it does, but not all. And the issue is that if I say `-DCMAKE_Fortran_COMPILER=mpifort` now suddenly *every* file in MAPL suddenly requires a user to use `mpirun` to run it since the wrapper is the Fortran compiler.

It was sort of a sin we had back in our GNU Make days. We'd hoped to move away from it in CMake.

**Comment by mathomp4** [comment]
Update on an old thread as I'm back in spack-land.

First, I can confirm I still get this issue with Darwin.gfortranclang. I then went to Discover and ran a test with GCC 12.1 and Open MPI 4.1.4 (so Linux.gfortran). That does *not* require the MPI wrappers.

So, perhaps it is just a Darwin.gfortranclang thing? Maybe I can figure out a way to "patch" ESMF inside of spack? 

@theurich Can you think up what your patch might be for this? (if it's simple, my fear is we might need a new script to extract the -L paths).

**Comment by billsacks** [comment]
I have submitted a suggested patch - see #159 . @mathomp4 can you try this out and let us know if it works for you? If so, @theurich you can let us know if you're comfortable with this: Even though it's debatable whether this "should" be needed, it seems like it won't do any harm, so I'm okay with adding this if you are.

**Comment by billsacks** [comment]
@mathomp4 I have merged the PR that I believe fixes this, which closed this issue. Please test it out when you get a chance; if it doesn't resolve your issue we can reopen it.

**Comment by mathomp4** [comment]
@billsacks Good news! The build seems happier! Now, one of the MAPL self-tests is failing, but I don't think I can put that on this, but rather on some other spack-related thing that I'll need @tclune help on.

But thanks to you, one step closer to replacing Baselibs with Spack!

**Comment by billsacks** [comment]
Great, thanks for confirming – I'm glad this solved your issue!
