### ISSUE TITLE
Change normalization value for bilinear interpolation maps?

### ISSUE THREAD

**Issue by czender** [esmf-org/esmf#170]
`ESMF_RegridWeightGen` adds the global attribute `normalization = "destarea" ;` to map-files produced by the `bilinear` interpolation algorithm.  This is confusing, since my understanding is that `destarea` only means something useful for conservative interpolation methods. In that case `destarea` means normalize by the destination area fraction (`frac_b`). For `bilinear` interpolation, the `destarea` algorithm is a no-op because area fractions are not involved in the calculation. This is mathematically equivalent to `frac_b=1`, though in reality bilinear interpolation does no normalization. Hence the `normalization = "destarea" ;` can confuse people. If you agree with this reasoning, please consider changing the `normalization = "none" ;` or something similar. Feedback or clarifications welcome. Also pinging @rljacob and @iulian787 who have encountered this issue.

**Comment by billsacks** [comment]
@czender - thanks a lot for reporting this. The ESMF core team discussed it this morning and agree that this should be changed. @oehmke 's suggestion was to use normalization = "N/A" for anything other than conservative maps; I plan to make the change to do that.

**Comment by czender** [comment]
Looking forward to it, thanks!
