### ISSUE TITLE
Apparent bug with ESMF_ConfigSetAttribute under NAG compiler

### ISSUE THREAD

**Issue by tclune** [esmf-org/esmf#171]
We detected this with our own variant SetAttribute() overloads, but verified that the problem is in ESMF routines as well.    I have a patch shown below, but have not investigated how the CPP token is defined within the ESMF build system.

The workaround was to change:
```f90
#ifdef ESMF_HAS_ACHAR_BUG
      character, parameter :: EOL = achar(12)   !! end of line mark (cr)
#else
      character, parameter :: EOL = achar(10)   !! end of line mark (newline)
#endif
```
to 
```f90
#if defined(ESMF_HAS_ACHAR_BUG) | defined(__NAG_COMPILER_BUILD)
      character, parameter :: EOL = achar(12)   !! end of line mark (cr)
#else
      character, parameter :: EOL = achar(10)   !! end of line mark (newline)
#endif
```

Might reflect a missing unit test as well ...

**Comment by tclune** [comment]
Best guess here is that the test is relatively new and was just never exercised by Darwin NAG.   Closing.

**Comment by tclune** [comment]
Reopening ...

I've now build a local ESMF using NAG compiler under Darwin and have verified that the default FPP branch works just fine in that environment.   Testing would be necessary to verify that this change does not break in any other environment but @theurich asserted that NAG+Darwin is the only case where `ESMF_HAS_ACHAR_BUG` is ever set, so ...   I'd suggest eliminating that setting entirely and cleaning the code a bit.   MAPL will then follow suit.

**Comment by theurich** [comment]
@tclune - can you say whether the `ESMF_HAS_ACHAR_BUG` branch breaks or does not break under Darwin/NAG with the latest NAG on your local machine?

**Comment by tclune** [comment]
With the latest NAG and the latest ESMF everything works.  (Not sure how I convinced myself otherwise on Monday - just not being careful enough I suppose.)

So technically ESMF is not broken, but I suggest you take my PR anyway as it does simplify the code and would appear to reduce risk going forward when external projects write their own SetAttribute().  But I'll understand if you reject ...

**Comment by theurich** [comment]
I do prefer simplifying the handling, but do want to break older NAG versions. Do you have previous NAG versions available to you on a Darwin system for testing?

**Comment by tclune** [comment]
We only use NAG for forward development.  Breaking older NAG is fine from our perspective.  (And I still have doubts about just when/where this actually was needed ...)      Indeed, on my current (new) laptop, I cannot access any older versions of NAG anyway ...

So the question is whether you have a user base that would be affected.  Seems unlikely.
