### ISSUE TITLE
Do these IO routines need additional calls to Array::destroy to avoid memory leaks?

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#174]
I noticed this in the course of working on the `IO::read` routine for #169 , but the same possible issue exists in `IO::write` (which I'm not touching in #169 ), so I'll reference the relevant code sections in that routine:

I see that there is a call to `Array::destroy` here if need_redist is true:

https://github.com/esmf-org/esmf/blob/afe445d1652514b958d2607e624c2ac9c40886fa/src/Infrastructure/IO/src/ESMCI_IO.C#L729-L733

This makes sense, because the need_redist logic would have led to a call to `redist_arraycreate1de`, which in turn creates the temp_array_p using this call to `Array::create`:

https://github.com/esmf-org/esmf/blob/afe445d1652514b958d2607e624c2ac9c40886fa/src/Infrastructure/IO/src/ESMCI_IO.C#L1268-L1272

However, there is currently *no* call to `Array::destroy` in the `has_undist` case, despite the fact that that case also spawns a new Array via a call to `undist_arraycreate_alldist`:

https://github.com/esmf-org/esmf/blob/afe445d1652514b958d2607e624c2ac9c40886fa/src/Infrastructure/IO/src/ESMCI_IO.C#L1400-L1406

Should there be an `Array::destroy` in that case, too, or is it unnecessary because of the aliasing that's done in that array creation (`DATACOPY_REFERENCE`)?

**Comment by theurich** [comment]
@billsacks - I do think that there should be an associated `ESMCI::Array::destroy()` for the `has_undist` case. With the `copyflag=DATACOPY_REFERENCE` specified during `ESMCI::Array::create()`, the array object knows to not deallocate the data region. 
One thing to check though is any caching that might be implemented wrt temporary Arrays that are created. I think there is some caching wrt the RouteHandle (which might also be different between Read/Write right now). And maybe there is some caching wrt Arrays. Just something to double check.

**Comment by billsacks** [comment]
Thanks for your thoughts on this, @theurich . I'll work on a fix for this.

Good point about checking caching. As you say, there is caching of the RH, though only on Writes. It looks like the caching is stored on the original array, so as far as I can tell, destroying the temporary Arrays won't mess with that. I don't see any other caching in these routines.

**Comment by billsacks** [comment]
> Good point about checking caching. As you say, there is caching of the RH, though only on Writes. It looks like the caching is stored on the original array, so as far as I can tell, destroying the temporary Arrays won't mess with that. I don't see any other caching in these routines.

I realized that there is also some caching (sort of) of the PIO IO Descriptor. A search for an already-created IO Descriptor is done by comparing the current Array with the Array pointer stored in the IO Descriptor object:

https://github.com/esmf-org/esmf/blob/b423b22ab1ea7c1ec3afee4468f800324afffee8/src/Infrastructure/IO/src/ESMCI_PIO_Handler.C#L2393-L2396

I think that destroying the temporary array (and recreating it later) will stop this caching from being able to work (which will, in turn, lead to a recreation of the PIO Decomposition). But this seems like a pre-existing issue that won't get any worse with my proposed new deletions.
