### ISSUE TITLE
Minor bug in HConfig

### ISSUE THREAD

**Issue by tclune** [esmf-org/esmf#175]
Consider the reproducer below.   An empty HConfig object is created, and a simple query is made to check for the presence of a key.   A nonzero return code is returned.

I believe that _either_ the Create() function should require one of `content` or `filename`, _or_ the accessor `IsCreated` should not throw an error.      Granted, the issue only really arises in synthetic situations (my unit tests), and adding in `content={}` is a pretty minor correction on my end.

Closely related, it is not sufficient to pass an empty string `''` as the content argument.   But I'm fine with using `{}`.

```f90
program main
   use esmf
   implicit none

   integer :: status
   type(ESMF_HConfig) :: hconfig
   logical found

   call esmf_initialize(rc=status)
   if (status/= 0) error stop __LINE__

   hconfig = ESMF_HConfigCreate(rc=status)
   if (status/= 0) error stop __LINE__

   found = ESMF_HConfigIsDefined(hconfig, keystring='a', rc=status)
   if (status/= 0) error stop __LINE__

   print*, 'found is ', found, ' (expected .false.)'

   if (status/= 0) error stop __LINE__

   call esmf_finalize(rc=status)
   if (status/= 0) error stop __LINE__
end program main
```

**Comment by theurich** [comment]
@tclune - After reviewing the current behavior I believe it is correct - but maybe needs better documentation.
Specifying the `keyString` optional argument requires that `hconfig` is a map. However, it is *not* a map, in fact it is `Null` after empty creation. That seems completely consistent to me. In other words, 
```
ESMF_HConfigIsMap(hconfig, rc=status)
```
would return `.false.`, and
```
ESMF_HConfigIsNULL(hconfig, rc=status)
```
would return `.true.`. So therefore
```
ESMF_HConfigIsDefined(hconfig, keystring='a', rc=status)
```
correctly returns `rc/=ESMF_SUCCESS`, as would a call with the `index` argument (expecting a `Sequence` in that case).

So I think the current behavior is strictly speaking the correct one. However, I do see your point from an ease-of-use perspective, where the user does not strictly care *why* they cannot access `keyString='a'`, just that it is not defined for what ever reason. To support this for convenience, following the rest of the ESMF API, we'd add argument `logical, intent(in), optional:: relaxedFlag`, that if set to `.true.` tells ESMF to not return an error under this condition. Instead just return `.false.` as the return value for what ever reason the request comes back negative. In your usage then, you'd just call with `relaxedFlag=.true.`.

**Comment by tclune** [comment]
@theurich Good point.   I've been spoiled by pyyaml.  (And my yaFyaml is based on that ...)    

With your clarification, I'm fine with the implementation as is.      I've already updated the various unit tests that pass an HConfig just because some interface requires it to use "{}" as the default content.  

Basically I'm happy to close the ticket ...
