### ISSUE TITLE
Workaround needed to build with Darwin intelclang configuration with XCode/clang 15 under Rosetta

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#193]
As reported by @mathomp4 - The latest version of XCode/clang (version 15) has an issue that requires a workaround to build ESMF on MacOS (Darwin) systems under Rosetta.

For others who run into this issue, a workaround that appears to resolve the issue is to set the following environment variables before building ESMF:
```
ESMF_CXXLINKOPTS='-Wl,-ld_classic'
ESMF_CLINKOPTS='-Wl,-ld_classic'
ESMF_F90LINKOPTS='-Wl,-ld_classic'
```

We are **not** planning to make these options the default, since this only affects limited configurations and will hopefully be fixed soon in Mac's clang, but wanted to document this workaround for others.

Thanks to @mathomp4 for extensive investigation and testing.

**Comment by billsacks** [comment]
This was opened just to document the issue. We do not plan to do anything about it, so closing as a wontfix.

**Comment by mathomp4** [comment]
Note that @tclune found he needed to do this with clang+gfortran-13 as well, while I didn't. So this might be something needed at various times if weird linking errors are found during build.

**Comment by billsacks** [comment]
Thanks @mathomp4 - I have updated the title and description accordingly.
