### ISSUE TITLE
Variable "localSsi" not declared

### ISSUE THREAD

**Issue by mhrib** [esmf-org/esmf#195]
Tried to compile ESMF v.8.6.0 on our HPC (HPE/Cray computer) using intel, gnu and cray compilers:

All returns errors, telling that the "localSsi" variable is not defined. The error is related/depending on the "`#ifdef ESMF_NO_GETHOSTID`" settings as far as I can see:

- **Intel**: PrgEnv-intel/8.4.0 , intel/2022.2.1
./esmf/src/Infrastructure/VM/src/ESMCI_VMKernel.C:708:22: error: use of undeclared identifier 'localSsi'
    for (auto i=0; i<localSsi; i++)

- **Cray**: PrgEnv-cray/8.4.0 , cce/16.0.1
./esmf/src/Infrastructure/VM/src/ESMCI_VMKernel.C:708:22: error: use of undeclared identifier 'localSsi'
    for (auto i=0; i<localSsi; i++)

- **Gnu**: PrgEnv-gnu/8.4.0module list , gcc-native/11.2
./esmf/src/Infrastructure/VM/src/ESMCI_VMKernel.C:708:22: error: ‘localSsi’ was not declared in this scope
     for (auto i=0; i<localSsi; i++)

---o---

Note:
The above compiles perfectly without setting `ESMF_NO_GETHOSTID`

**Comment by theurich** [comment]
@mhrib, yep, it does look like we broke the `ESMF_NO_GETHOSTID` option.
Just curious, are you typically building with that option enabled, and if so why is that? How critical is this option for you? Thanks.

**Comment by mhrib** [comment]
@theurich
>Just curious, are you typically building with that option enabled, and if so why is that? How critical is this option for you? Thanks.
It is absolutely not critical for us. Indeed, we don't have to build with that option and will not do it forward in time. For us it is ok to skip the option if this was the question?

The `ESMF_NO_GETHOSTID` option was a leftover in our settings-files used on one of our former HPC's - a Cray XT4 as far as I can read from a comment-line. So we're talking 15 years back or even more :-) Likely due to an error within the compiler used at that time.

**Comment by theurich** [comment]
@mhrib 

Thank you for providing the details... that all makes sense about the Cray XT4 history on using that flag. Very good to know you will not be building with that flag forward going... which is definitely our recommendation, too!

Just FYI, the code around the `ESMF_NO_GETHOSTID` macro is fixed again on the ESMF develop branch, just in case a need for it arises on some particular system. But again we do recommend NOT using it unless absolutely needed.
