### ISSUE TITLE
ESMF should not export `C_PTR`

### ISSUE THREAD

**Issue by tclune** [esmf-org/esmf#197]
I just accidentally discovered a "bug" wherein one of my Fortran modules did not import `C_PTR` from `ISO_C_BINDING`.   Was wondering why it compiled in the original environment and discovered that ESMF provides `CPTR`.

Is this intended?

**Comment by tclune** [comment]
Apparently `c_f_pointer` is an issue as well.

**Comment by theurich** [comment]
@tclune Making `C_PTR` and `C_F_POINTER` from `ISO_C_BINDING`  (or any other 3rd party symbol for that matter) public via `use ESMF`is **not** done by intention. It is a bug. We'll work on fixing it. Thank you for letting us know!

**Comment by tclune** [comment]
NP.     Am guessing it means you have missing default PRIVATE on some module somewhere ...

**Comment by theurich** [comment]
Yep, that's my guess, too. I already see a few places... too many cooks... :-)

**Comment by theurich** [comment]
@tclune Just to let you know that this is fixed now (on `develop`). I.e. the symbols of the `ISO_C_BINDING` are no longer made public via the `ESMF` module. As suspected there were a few `private` statements missing.
