### ISSUE TITLE
Investigate coupling a Julia-based model and put in place a test exercising this coupling

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#210]
There is interest in coupling a Julia-based wave model as an alternative to WW3 in CESM. I will do some initial investigation to determine if there are major roadblocks to doing this.

**Comment by billsacks** [comment]
Assuming I can get this working, I will also put in place a test exercising this coupling, building on the work for https://github.com/esmf-org/esmf-support/issues/228.

**Comment by anntsay** [comment]
this is part of NUOPC-app-prototype.

**Comment by billsacks** [comment]
Done in https://github.com/esmf-org/nuopc-app-prototypes/pull/5
