### ISSUE TITLE
Change needed in FindESMF.cmake

### ISSUE THREAD

**Issue by mathomp4** [esmf-org/esmf#225]
In working with @AlexanderRichert-NOAA on trying to get the `ESMF::ESMF` target into MAPL, I think I ran into a CMake limitation. Namely, when we build MAPL, CMake autogenerates a `MAPL-targets.cmake` file and in there we see:
```cmake
set_target_properties(MAPL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/MAPL"
  INTERFACE_LINK_LIBRARIES "MAPL.base;MAPL.generic;MAPL.pfio;MAPL_cfio_r4;MAPL.gridcomps;MAPL.orbit;MAPL.griddedio;MAPL.field_utils;ESMF;NetCDF::NetCDF_Fortran;MPI::MPI_Fortran;\$<\$<BOOL:OFF>:FLAP::FLAP>"
)
```
The issue is that in this we see that `ESMF` not `ESMF::ESMF` is in the `INTERFACE_LINK_LIBRARIES`. As far as I know, the only target that ever gets placed in here is the "actual" library target defined in `FindESMF.cmake`, which is `ESMF`. [Alias targets](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#alias-targets) are convenient but not "real".

So, I think what needs to be done is rather `ESMF::ESMF` is the main target supplied by `FindESMF.cmake` and instead we do:
```cmake
  if(NOT TARGET ESMF)
    add_library(ESMF ALIAS ESMF::ESMF)
  endif()
```
essentially "reversing" the current one.

That said, I think I've broken the Baselibs build testing this, so I'll need to debug a bit more...

---

Related PRs:

- https://github.com/GEOS-ESM/ESMA_cmake/pull/354
- https://github.com/GEOS-ESM/MAPL/pull/2599

**Comment by oehmke** [comment]
Hi @mathomp4 , We talked about this at our ESMF meeting today. Would you mind explaining a bit more what this (and associated PRs) is fixing?  Also, is this tested and finished? It wasn't clear to me from the comments if it's done yet. Thanks!

**Comment by mathomp4** [comment]
@oehmke As the main comment says, the issue is that our UFS friends are often picking up an `ESMF` target via our `MAPL-targets.cmake` file that is generated when you build MAPL.

Now, internally, MAPL is now using `ESMF::ESMF` as the only target used in CMake even before this change. But @AlexanderRichert-NOAA found that [he could not `spack install mapl`](https://github.com/spack/spack/pull/42619#pullrequestreview-1875864697) when we made that target change. Baselibs builds are fine, spack wasn't.

So I did some testing and found that the issue was that we essentially need to have `ESMF::ESMF` be the original target provided by `FindESMF.cmake`. That "original" target has a status in CMake but aliases of that target are sort of second-class. You can't do things with them that the originally defined target can.

And if I build and run with this new `FindESMF.cmake` using Baselibs, all is well. GEOS builds, runs, and in the `MAPL-target.cmake` file, I see `ESMF::ESMF`. This all works because I include two different copies of this altered `FindESMF.cmake` file in ESMA_cmake and MAPL itself. And our Baselibs builds of GEOS/MAPL see this new file.

But the issue in the *Spack* build of MAPL is that Spack is smarter than I gave it credit for and it's finding and using the `FindESMF.cmake` from ESMF itself rather than the ones I carry. So it was still finding the one from here and then supplying `ESMF` as the "main" target.

I think with this change -- make `ESMF::ESMF` the main target and `ESMF` an alias -- all will be happy.

I could work with @AlexanderRichert-NOAA to have him test the spack-side of this if you'd like.

**Comment by mathomp4** [comment]
@danrosen25 Here is the official one:

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mapl/package.py

You can see what I was trying to do to update it in https://github.com/spack/spack/pull/42619 but that's when @AlexanderRichert-NOAA informed me it was broken.
