### ISSUE TITLE
ESMPy test, test_locstream_grid_regrid, can have unpredictable behavior

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#227]
I went down a bit of a rabbit hole today investigating why I was getting failures in the ESMPy test, test_locstream_grid_regrid, on my Mac. The tolerance for the error check in this test is 9e-5, and the error on derecho (with both intel and gfortran, with python3.10) is 8.97e-5, but on my Mac (with gfortranclang, with both python3.10 and python3.11) is 9.31e-5. I was about to simply increase the tolerance (to 1e-4) and move on, but then (maybe foolishly) decided to dig a big deeper to see if there was something more than just machine precision differences going on here – and indeed, I found some weirdness in this test that explains the difference.

This test is implemented in https://github.com/esmf-org/esmf/blob/develop/src/addon/esmpy/examples/locstream_grid_regrid.py. It looks like it's regridding from a locstream (with 16 points) to a gridded destination field using NEAREST_DTOS, which I'm thinking says: for each source point, find the nearest destination point and put the source value there. But what I think leads to this unpredictable behavior is that the locstream is set up with 4 points on the south pole and 4 points on the north pole, in addition to 8 non-pole points. (There are duplicate non-pole points as well because, for each of the two other latitudes, there are points with longitude = 0 and longitude = 360... that feels kind of funny, but I don't think it causes any issues.) It turns out that, on derecho, the nearest destination point to the 4 south pole points is chosen to be (-89.5°N, 3°E), whereas on my Mac, the nearest destination point is chosen to be (-89.5°N, 87°E). Those seem like equally good choices, so I'm not surprised that there could be machine differences in this choice. The resulting dstfield value is the same on both my Mac and derecho, but the xctfield ("exact field" - i.e., the expected value) differs betwene the 3°E and the 87°E points, resulting in differences in the relative error value.

I'd love input on how to move forward here from someone familiar with what this is trying to test. Specifically: The easy fix here would be for me to just increase the tolerance of this test a bit and move on. But I wonder if we should address this oddity that might crop up again in the future, by rewriting the locstream creation functions in https://github.com/esmf-org/esmf/blob/develop/src/addon/esmpy/src/esmpy/util/locstream_utilities.py. Is it intentional to have these exact pole points as well as having duplicate points in the locstream that is used in this test and a few other tests, or should this be changed to avoid these pole points & duplicate points?

**Comment by oehmke** [comment]
Thanks for going down the rabbit hole on this. :-)   I’m running out of time to look at this today, but I’ll think about it next week and get back to you. (I’ll add it to my todo list, but if I don’t get back, feel free to remind me later in the week.)

**Comment by billsacks** [comment]
Just a note for future reference: Even though I think the duplicate non-pole points didn't cause issues of unpredictable behavior, I think those duplicate points led to large relative errors because the destination field ended up having values twice that of the source points (since two source points would get mapped to a given destination point). In the commit where I fixed this, I have also removed these duplicate points, reducing the expected relative errors.
