### ISSUE TITLE
 ESMF_TimeSyncToRealTime() add no leap and maybe other calendar restrictions

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#230]
ESMF_TimeSyncToRealTime() returns with an error on leap days for the no leap calendar. Return an error if a Time with that Calendar type is used is used in that method. Also, look through and see if there are further calendars that should be restricted for the same reason.

**Comment by anntsay** [comment]
Ufuk is creating a reproducer.    will then try to trigger the same error in a docker container.

**Comment by uturuncoglu** [comment]
This is fixed with https://github.com/esmf-org/esmf/pull/236
