### ISSUE TITLE
Remove NR code

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#239]
Remove any NR code from the library.

**Comment by anntsay** [comment]
Bill volunteered.

**Comment by anntsay** [comment]
The tool is moss - https://theory.stanford.edu/~aiken/moss/

https://github.com/esmf-org/esmf/blob/develop/LICENSE

**Comment by anntsay** [comment]
Bob: this has a good test coverage for this function.. so we could check the code modification.

**Comment by anntsay** [comment]
Moab has not changed anything.  Zoltan has removed reference and folder restructured.

**Comment by billsacks** [comment]
> Zoltan has removed reference and folder restructured.

In particular, it looks like Zoltan has removed the sort functions that were the main sources of references to NR (or at least moved / renamed them to places where I couldn't quickly find them).

**Comment by billsacks** [comment]
Resolved by 03d0eb5fc0
