### ISSUE TITLE
adding --netcdf4 option to ESMF_Regrid (option already available using CLT ESMF_RegridWeightGen)

### ISSUE THREAD

**Issue by jvmcgovern** [esmf-org/esmf#264]
Hi there,

I recently identified an issue where when I was interpolating to a large output netcdf, the .log file would indicate that I never got the line "Finalizing ESMF". 

Is it possible to add netcdf4 capability to the ESMF_Regrid CLT options as with ESMF_RegridWeightGen? 

Best regards

**Comment by anntsay** [comment]
it seems that the code touch many places,

**Comment by billsacks** [comment]
> it seems that the code touch many places,

Finishing that comment: we felt last week that this would be too large of a change to make it into the upcoming 8.8 release. But we plan to at least get it into 8.9.

Thank you for reporting this, @jvmcgovern .

**Comment by billsacks** [comment]
@jvmcgovern I have been looking into this today. I do not have experience using ESMF_Regrid myself, so I may be missing something here, but I think that the different behavior of ESMF_Regrid means that this argument is unnecessary. Specifically: It looks like the typical operation of ESMF_Regrid is to provide an existing destination grid file, and then ESMF_Regrid adds a variable to this existing file. (This is in contrast with ESMF_RegridWeightGen, where a new file is created.) Does that sound right to you in your use case?

If so, I think the solution is to change the file type of the destination file before running ESMF_Regrid. This can be done, for example, with the NetCDF Operators (NCO) tool nccopy:

```
nccopy -k nc4 original.nc new.nc
```

Please let us know if this will resolve your issue.

**Comment by billsacks** [comment]
I'm going to close this as a wontfix based on the comment above, but @jvmcgovern feel free to comment and reopen if you feel this hasn't resolved your issue.

**Comment by billsacks** [comment]
Thanks for the reply @jvmcgovern . Yes, it would be great to have your confirmation that this solves your problem whenever you get a chance to test it. Once you do, I agree that we should document this, and I'm happy to do so.

**Comment by jvmcgovern** [comment]
[like]  Joe McGovern reacted to your message:
________________________________
