### ISSUE TITLE
fieldList in ESMF_FieldBundleWrite is not deallocated

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/esmf#280]
There's no deallocation for the fieldList created in ESMF_FieldBundleWrite, this would cause a memory leak.

https://github.com/esmf-org/esmf/blob/fda68a9ac3b599065207f9c95c92e05d90fe6b78/src/Infrastructure/FieldBundle/src/ESMF_FieldBundle.cppF90#L7018

**Comment by theurich** [comment]
The local `fieldList` variable is defined at https://github.com/esmf-org/esmf/blob/fda68a9ac3b599065207f9c95c92e05d90fe6b78/src/Infrastructure/FieldBundle/src/ESMF_FieldBundle.cppF90#L6969 as an `allocatable`. This means that Fortran will take care of the deallocation automatically.

**Comment by danrosen25** [comment]
Well they say you learn something new every day. I didn't know that Fortran automatically deallocates an allocatable as it exits the scope of a subroutine. I thought it was like C code. We can close this issue.
