### ISSUE TITLE
Fix ESMX - link_module_paths, two stage appConf

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/esmf#281]
While attempting to link Julia_LIBRARY into ESMX_SingleModelInJuliaProto a few bugs were discovered

- add module paths wrong variable name `ESMX_CMAKE_MODULE_PATHS` should be `ESMX_LINK_MODULE_PATHS`
- due to variable expansion ${Julia_LIBRARY} cannot be used until after find_package(Julia)
- link_libraries can't find a library if the full path is given

Code changes are ready for review on fork: https://github.com/danrosen25/esmf/tree/fix/esmx_app_link

Julia prototype changes once ESMX changes are merged
[julia_ld_cleanup.patch](https://github.com/user-attachments/files/16787842/julia_ld_cleanup.patch)

**Comment by danrosen25** [comment]
Hi @billsacks I completed the changes needed other than renaming the user facing configuration options. We should discuss these configuration option name changes with @theurich before proceeding

- link_module_paths -> append_module_paths
- link_packages -> find_packages

**Comment by billsacks** [comment]
This is great @danrosen25 - thank you very much for getting this working! I like this way of handling this linking to Julia.

In addition to your changes, we should change this section of the README in nuopc-app-prototypes; I can do that once we're ready to bring in these changes:

https://github.com/esmf-org/nuopc-app-prototypes/tree/develop/ESMX_SingleModelInJuliaProto#specifying-build-options-needed-to-invoke-julia-code
