### ISSUE TITLE
Additional NUOPC_Connector metadata

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf#300]
There are a few more settings we need to support on the generic NUOPC_Connector via attributes:

- A flag to disable VMEpoch usage. It cannot just be ON/OFF, because NUOPC_Connector makes its own decision on whether VMEpoch can be turned ON/OFF (according to the limitation that VMEpoch is currently supported for disjoint send/recv petLists). But this option should allow the user to disable any usage of VMEpoch, even if NUOPC_Connector could turn it ON. On the other hand the option should not suggest to the user that they have a way to force the usage of VMEpoch.
- We already have the `EpochThrottle` option exposed. We need to also expose the `EpochEnterKeepAlloc` and `EpochExitKeepAlloc` 

In the `ConnectionOptions` attribute
- We already have `dumpWeights`. We need something like `dumpCommMatrix` to allow dumping of the communication matrix that is available on each RH. Not sure exactly how filename is specified here... need to think about that also for `dumpWeights`.

**Comment by danrosen25** [comment]
@anntsay 
This looks like connector metadata being used internally. I'm not sure this is field metadata. Is it?

**Comment by anntsay** [comment]
Hi Dan, Got it. thanks for pointing that out.  so basically this sounds like it is to expand the NUOPC_Connector attributes. so i think you are right.  @theurich could you confirm?

**Comment by anntsay** [comment]
Gerhard: is motivated to have this in.

**Comment by theurich** [comment]
Completed the first part of this by completing the EPOCH related metadata on the NUOPC_Connector component kind:

- `EpochEnable` (new)
- `EpochEnterKeepAlloc` (new)
- `EpochExitKeepAlloc` (new)
- `EpochThrottle` (was there before)

However, the second part, that deals with the `ConnectionOptions` extensions, will require more work. It is now tracked as #334.
