### ISSUE TITLE
Python yaml module in ESMX build

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#305]
There has been an issue in a few places where the ESMX build grabs a different python than one that's already in use and that python doesn't have pyyaml installed so it fails. 

One example of this was in our testing on Orion where our python/yaml based test system was working, but then the ESMX nuopc protos failed because they grabbed a different Python that didn't have yaml. 

Also, one of our collaborators on the SWORD project was having this issue (see email below). (@uturuncoglu  and @anntsay are also interested in this issue from that project.) 

Obviously, one solution is just to install yaml in the python that CMake is grabbing. However, I wonder if it would be possible to have CMake just use the default/current python if one exists, so this doesn't have to be done. 

Thanks!

===== Email =====

Hi Ufuk,

So I installed pyyaml with

pip install pyyaml

and if I try to run the script interactively

python /Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_app_config.py -h

it works fine. If I change the

import yaml

line in  /Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_tools.py to

import yamlxx

then it fails

 File "/Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_tools.py", line 4, in <module>
   import yamlxx
ModuleNotFoundError: No module named 'yamlxx'

so clearly, I have yaml in my Python distribution. Still, if I execute

make test_esmf

it fails with

/Users/gtoth/ESMF_nagfor/bin/bing/Darwin.nag.64.mpich.default/ESMX_Builder --prefix=/Users/gtoth/Tmp_nag/SWMF --verbose
Settings:

 ESMX_BUILD_FILE=esmxBuild.yaml
 ESMF_ESMXDIR=/Users/gtoth/ESMF_nagfor/include/ESMX
 ESMFMKFILE=/Users/gtoth/ESMF_nagfor/esmf.mk
 BUILD_DIR=/Users/gtoth/Tmp_nag/SWMF/ESMF/ESMF_SWMF/src/build
 INSTALL_PREFIX=/Users/gtoth/Tmp_nag/SWMF
 BUILD_TYPE=release
 BUILD_ARGS=
 DISABLE_COMPS=
 BUILD_JOBS=
 MODULEFILE=
 BASHENV=
 TEST=false
 TEST_ARGS=
 VERBOSE=true

-- Detected ESMF Beta snapshot: 0
-- Detected ESMF Beta snapshot: 0
Traceback (most recent call last):
 File "/Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_app_config.py", line 4, in <module>
   from esmx_tools import *
 File "/Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_tools.py", line 4, in <module>
   import yaml
ModuleNotFoundError: No module named 'yaml'
CMake Error at Driver/CMakeLists.txt:12 (message):
 esmx_app_config.py failed processing esmxBuild.yaml
Call Stack (most recent call first):
 Driver/CMakeLists.txt:34 (esmx_check_ret)

so in this case "yaml" is not found. Since I do the make test_esmf as myself, I don't understand how it is succeeding to find yaml in on case and failing in the other. Are you potentially using a fixed python version? For example, if I switch from 3.11 to 3.10 I get

<mesh:~/Tmp_nag/SWMF>python3.10 /Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_app_config.py -h
Traceback (most recent call last):
 File "/Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_app_config.py", line 4, in <module>
   from esmx_tools import *
 File "/Users/gtoth/ESMF_nagfor/include/ESMX/Driver/esmx_tools.py", line 4, in <module>
   import yaml
ModuleNotFoundError: No module named 'yaml'

Clearly, it would be a good idea to use the default python version.

Gabor

**Comment by danrosen25** [comment]
@oehmke @uturuncoglu 
This issue is specific to the installation of python. The default for `find_package(python ...)` uses `Python_FIND_FRAMEWORK="FIRST"` so you end up looking through framework paths and using NO_SYSTEM_ENVIRONMENT_PATH. I can change `Python_FIND_FRAMEWORK="LAST"` in ESMX and it should search standard paths before framework paths.

**Comment by anntsay** [comment]
Bob we also saw this on Orion, but this was fixed in another way.

Dan has a fixed PR and needs review.   and has already tested on his local machine.. (hard to replicate).

Ufuk: Gabor has a successful installation now by installing a new version Pyyaml
