### ISSUE TITLE
Wrong error message from ESMCI_MeshDual.C

### ISSUE THREAD

**Issue by MuellerSeb** [esmf-org/esmf#317]
https://github.com/esmf-org/esmf/blob/9313a45e2add8b2cdad0b9a55aaf4096d535aaa7/src/Infrastructure/Mesh/src/ESMCI_MeshDual.C#L108

This should say:
> Creation of a dual mesh isn't supported for Meshes of parametric dim greater than 2.

2 not 3.

**Comment by oehmke** [comment]
Thanks for reporting this! I fixed it, so closing issue.
