### ISSUE TITLE
Create initial ESMX layer and initial unified driver

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf#64]

**Comment by theurich** [comment]
The initial implementation of the ESMX layer has been completed and is part of the ESMF distribution under [./src/addon/ESMX](https://github.com/esmf-org/esmf/tree/develop/src/addon/ESMX). Initial documentation is provided in form of a README.md on the ESMX layer.

Two ESMX prototypes were also added to the NUOPC application protos:

- [ESMX_AtmOcnProto](https://github.com/esmf-org/nuopc-app-prototypes/tree/develop/ESMX_AtmOcnProto)
- [ESMX_ExternalDriverAPIProto](https://github.com/esmf-org/nuopc-app-prototypes/tree/develop/ESMX_ExternalDriverAPIProto)

The initial version of ESMX is planned for release and announcement with ESMF 8.4.0.
