### ISSUE TITLE
ESMF and ESMPy on Apple M1 Silicon

### ISSUE THREAD

**Issue by jkrasting** [esmf-org/esmf#74]
I am attempting to build ESMF and ESMPy on M1 (arm64) with macOS Monterey.  I feel like I am close, but I am running into two problems:

My environment is:

- Git branch:  develop (v8.4.0b14, fa38353)
- Fortran: GNU Fortran (Homebrew GCC 12.2.0) 12.2.0
- CXX:  Apple clang version 14.0.0 (clang-1400.0.29.102)
- (The output of [gmake_info.txt](https://github.com/esmf-org/esmf/files/9626700/gmake_info.txt) is attached)

Issue 1:

I get a few type mismatch errors in this environment that do not appear when I try compiling with GCCv12 via homebrew. I can bypass them for now via `ESMF_F90COMPILEOPTS += -fallow-argument-mismatch`.  The library seems to compile OK once bypassing the mismatches.  (Note: I would compile with GCCv12 from homebrew except I run into linker errors that I can't seem to untangle.)

Issue 2:

After building and installing ESMF, I am trying to install ESMPy.  (The newly added `pip install .` is great btw!). It appears to install correctly, but I end up with library errors when I try to import ESMF.

```
>>> import ESMF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/interface/cbindings.py", line 1368, in <module>
    _ESMF.ESMC_MeshGetLocalElementCount.restype = ct.c_int
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x205084200, ESMC_MeshGetLocalElementCount): symbol not found
```

Any thoughts or suggestions on these? Thanks!

**Comment by rsdunlapiv** [comment]
@jkrasting we have been recently looking into whether we can support the Apple clang compiler. At best, we've gotten mixed results so far, so you should be aware that even if we resolve the second error with ESMPy, I am not confident that the resulting system will be stable. If you run "make all_tests" after building ESMF, you will likely see a number of failures from our internal test suite.

The safest option at the moment is to switch from clang to another compiler such as GNU g++. My understanding is that it takes some "convincing" of your system to have it use g++ over clang, but it can be done. @billsacks can likely provide some more insight on that part.

We would definitely *like* to support Apple clang so that you can build ESMF/ESMPy "out of the box" on an M1. That being said, we've found a number of comments online about issues related to Fortran/C++ language interoperability with clang. If this is the case, there may be issues that we could not easily work around.

**Comment by rokuingh** [comment]
@jkrasting wrt to the python layer, along with the addition of a pip installation, we also renamed the module from ESMF to esmpy. The fact that you are importing ESMF could imply that you are accessing an old installation. We have also switched from nose to pytest, so once you work through the ESMF build issues with clang/gcc, and then update your esmpy installation, you can try something like this:
`python3 -m pytest -vs`

**Comment by jkrasting** [comment]
Thanks for the clarification @rokuingh.

I tried your setup, @billsacks, but I still run into linker issues.  

`libesmf.a` builds fine, but there are issues with `libesmf.dylib`, `libesmf_fullylinked.dylib`, and `libesmftrace_preload.dylib`:

e.g.:
```
0  0x1026581a0  __assert_rtn + 140
1  0x1024dfa8c  mach_o::relocatable::Parser<arm64>::parse(mach_o::relocatable::ParserOptions const&) + 4536
2  0x1024b1d38  mach_o::relocatable::Parser<arm64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 148
3  0x10251a4ac  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 1468
4  0x10251d360  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 56
5  0x1900601f4  _dispatch_client_callout2 + 20
6  0x190073954  _dispatch_apply_invoke + 224
7  0x1900601b4  _dispatch_client_callout + 20
8  0x190071a04  _dispatch_root_queue_drain + 680
9  0x190072104  _dispatch_worker_thread2 + 164
10  0x190220324  _pthread_wqthread + 228
A linker snapshot was created at:
	/tmp/libesmf.dylib-2022-09-22-150158.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
```

**Comment by billsacks** [comment]
Thanks for posting the error message. That is an issue with the latest version of XCode that is not ESMF-specific.

For the fix (which involves downgrading to the previous version of XCode), see the answer here: https://stackoverflow.com/questions/73714336/xcode-update-to-version-2395-ld-compile-problem-occurs-computedatomcount-m (I haven't tried it yet myself). See also some of the comments toward the end of https://github.com/Homebrew/discussions/discussions/3659 .

**Comment by jkrasting** [comment]
After much trial and error, I did manage to build ESMF on M1.  Here are some additional notes regarding my experience:

- I rolled back Xcode to v13.4.  I am not fully convinced this is an issue, however.  I ran into similar error messages building other codes (e.g. MOM6) and we uncovered that the configure script from one of our shared libraries was picking up a different version of `ar`.  This might also be a case in ESMF with all of the different `configure` and `Makefile` scripts in the build tree.
- Using prebuilt libraries from both Homebrew and Macports gave unpredictable results
- Although more time consuming, the most reliable path for me was to use Macports and build gcc, openmpi, and netcdf locally from source, e.g. `sudo port -s install <pkg>`
- I had success with v8.2.0, v8.3.1, and the current `develop` branch
- Similar to @billsacks, I had 6 unit test failures. Everything else passed

I would really like to use v8.3.1 with Python but I am now running into a different issue with `ESMP_Initialize`.  I'll file a separate issue for that one.

**Comment by billsacks** [comment]
@jkrasting thank you for posting this follow-up. Is the remaining issue for you the one in #75 ? If so, I will close this issue.

I am continuing to work on trying to get ESMF working with Apple's clang compiler. If I can get this working (which may or may not be possible), this should hopefully make building & running on a Mac easier moving forward.

**Comment by jkrasting** [comment]
Yes, thanks @billsacks!
