### ISSUE TITLE
nvhpc port 

### ISSUE THREAD

**Issue by jedwards4b** [esmf-org/esmf#85]
We need to port ESMF to the nvhpc compiler (pgi followon)

**Comment by billsacks** [comment]
This is working to some extent, though there are some test failures that we need to investigate. We are doing nightly testing with nvhpc on cheyenne. Most (but not quite all) tests pass in optimized mode but we still have a lot of failures in debug mode that we need to investigate. (See latest test results here: http://earthsystemmodeling.org/esmf-test-summary/develop/index.html )

@jedwards4b are there particular issues you have encountered with CESM?

**Comment by jedwards4b** [comment]
My apologies, I think I made an incorrect assumption.  I see it is available and will try it.
