### ISSUE TITLE
oneapi support 

### ISSUE THREAD

**Issue by jedwards4b** [esmf-org/esmf#86]
We need to port to the new intel compiler - we are calling this oneapi to distinguish it from the current intel compiler set.

**Comment by jedwards4b** [comment]
I think maybe just setting ESMF_COMPILER=intel will work here, trying that now.

**Comment by theurich** [comment]
@jedwards4b it is my understanding that Intel's OneAPI continues to work with ESMF_COMPILER=intel. And if you use IntelMPi then also set ESMF_COMM=intelmpi. 
See this [summary.dat](https://github.com/esmf-org/esmf-test-artifacts/blob/170d98e3ffafa7157d8239e94dd03df2bf94ad0e/develop/intel/2021.2/O/intelmpi/2021.2.0-gcc-9.3.0/summary.dat) for an example of nightly testing with Intel OneAPI.

**Comment by jedwards4b** [comment]
Yes that does appear to be working.

**Comment by jedwards4b** [comment]
Where do I find these test artifacts for other compilers?  nvhpc for example?

**Comment by theurich** [comment]
http://earthsystemmodeling.org/esmf-test-summary/index.html is the main entry page into the nightly regression testing. Follow the link for the branch you want to see testing for. That will get you to the table with all the combos and artifact links.
