### ISSUE TITLE
Problem with file type detection

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#94]
The type detection checks for Gridspec first using the type of units. This can cause a scrip file to look like a gridspec file. Probably it would be better to look for specific variables first and then look at units. 

Also, add back in the src and dst file types to ESMF_RegridWeightGen, so a user can force a file type.

**Comment by billsacks** [comment]
The easier piece might be adding back in the src and dst file types as explicit argument... probably start with that.
